Source code from Koen Derks GitHub of his canvas_mesh function. Will deconstruct from a function into plain script 

What does :: mean?? 
```{r KD save ex}
# to save art. Eliminates wait time if saved directly to file 
artwork <- canvas_strokes(colors = c("black", "white"))
saveCanvas(artwork, filename = "myArtwork.png")
```


```{r kd internal function}
# Copyright (C) 2021-2023 Koen Derks

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This function generates noise
.noise <- function(dims, n = 100, type = c("artsy-knn", "knn", "svm", "rf", "perlin", "cubic", "simplex", "worley"),
                   k = 20, limits = c(0, 1)) {
  type <- match.arg(type)
  if (type == "artsy-knn") {
    if (length(dims) == 1) {
      vec <- expand.grid(limits[1], seq(limits[1], limits[2], length.out = dims))
    } else if (length(dims) == 2) {
      vec <- expand.grid(seq(limits[1], limits[2], length.out = dims[1]), seq(limits[1], limits[2], length.out = dims[2]))
    }
    z <- cpp_knn(stats::runif(n), stats::runif(n), stats::runif(n), vec[, 1], vec[, 2], k)
  } else if (type == "svm") {
    train <- data.frame(
      x = stats::runif(n, limits[1], limits[2]),
      y = stats::runif(n, limits[1], limits[2]),
      z = stats::runif(n, limits[1], limits[2])
    )
    fit <- e1071::svm(formula = z ~ x + y, data = train)
    xsequence <- seq(limits[1], limits[2], length = dims[1])
    ysequence <- seq(limits[1], limits[2], length = dims[2])
    canvas <- expand.grid(xsequence, ysequence)
    colnames(canvas) <- c("x", "y")
    z <- predict(fit, newdata = canvas)
  } else if (type == "knn") {
    train <- data.frame(
      x = stats::runif(n, limits[1], limits[2]),
      y = stats::runif(n, limits[1], limits[2]),
      z = stats::runif(n, limits[1], limits[2])
    )
    fit <- kknn::train.kknn(formula = z ~ x + y, data = train, kmax = k)
    xsequence <- seq(limits[1], limits[2], length = dims[1])
    ysequence <- seq(limits[1], limits[2], length = dims[2])
    canvas <- expand.grid(xsequence, ysequence)
    colnames(canvas) <- c("x", "y")
    z <- predict(fit, newdata = canvas)
  } else if (type == "rf") {
    train <- data.frame(
      x = stats::runif(n, limits[1], limits[2]),
      y = stats::runif(n, limits[1], limits[2]),
      z = stats::runif(n, limits[1], limits[2])
    )
    fit <- randomForest::randomForest(formula = z ~ x + y, data = train)
    xsequence <- seq(limits[1], limits[2], length = dims[1])
    ysequence <- seq(limits[1], limits[2], length = dims[2])
    canvas <- expand.grid(xsequence, ysequence)
    colnames(canvas) <- c("x", "y")
    z <- predict(fit, newdata = canvas)
  } else if (type == "perlin") {
    z <- ambient::noise_perlin(dims, frequency = stats::runif(1, 0.001, 0.04))
    z <- (z - range(z)[1]) / diff(range(z)) * diff(limits) + limits[1]
  } else if (type == "cubic") {
    z <- ambient::noise_cubic(dims, frequency = stats::runif(1, 0.001, 0.04))
    z <- (z - range(z)[1]) / diff(range(z)) * diff(limits) + limits[1]
  } else if (type == "simplex") {
    z <- ambient::noise_simplex(dims, frequency = stats::runif(1, 0.001, 0.04))
    z <- (z - range(z)[1]) / diff(range(z)) * diff(limits) + limits[1]
  } else if (type == "worley") {
    z <- ambient::noise_worley(dims)
    z <- (z - range(z)[1]) / diff(range(z)) * diff(limits) + limits[1]
  }
  return(matrix(z, nrow = dims[1], ncol = dims[2]))
}

# This function performs validation checks on the standardized input arguments of a function
.checkUserInput <- function(background = NULL, resolution = NULL, iterations = NULL) {
  if (!is.null(background) && length(background) != 1) {
    stop("'background' must be a single character")
  }
  if (!is.null(resolution) && (resolution < 1 || resolution %% 1 != 0)) {
    stop("'resolution' must be a single value > 0")
  }
  if (!is.null(iterations) && (iterations < 1 || iterations %% 1 != 0)) {
    stop("'iterations' must be a single integer > 0")
  }
}

# This function turns a matrix into a data frame with columns x, y, and z
.unraster <- function(x, names) {
  newx <- data.frame(x = rep(seq_len(ncol(x)), times = ncol(x)), y = rep(seq_len(nrow(x)), each = nrow(x)), z = c(x))
  colnames(newx) <- names
  return(newx)
}

# This function takes a point (x, y) and returns a warped point (x, y)
.warp <- function(p, warpDistance, resolution, angles = NULL, distances = NULL) {
  if (is.null(angles)) {
    angles <- .noise(c(resolution, resolution), type = sample(c("svm", "perlin", "cubic", "simplex"), size = 1), limits = c(-pi, pi))
  } else if (is.character(angles)) {
    angles <- .noise(c(resolution, resolution), type = angles, limits = c(-pi, pi))
  } else if (is.matrix(angles)) {
    if (nrow(angles) != resolution || ncol(angles) != resolution) {
      stop(paste0("'angles' should be a ", resolution, " x ", resolution, " matrix"))
    }
  }
  if (is.null(distances)) {
    distances <- .noise(c(resolution, resolution), type = sample(c("knn", "perlin", "cubic", "simplex"), size = 1), limits = c(0, warpDistance))
  } else if (is.character(distances)) {
    distances <- .noise(c(resolution, resolution), type = distances, limits = c(0, warpDistance))
  } else if (is.matrix(distances)) {
    if (nrow(distances) != resolution || ncol(distances) != resolution) {
      stop(paste0("'distances' should be a ", resolution, " x ", resolution, " matrix"))
    }
  }
  return(matrix(c(p[, 1] + c(cos(angles)) * c(distances), p[, 2] + c(sin(angles)) * c(distances)), ncol = 2))
}

# This function returns a brownian motion line
.bmline <- function(n, lwd) {
  x <- cumsum(stats::rnorm(n = n, sd = sqrt(1)))
  x <- abs(x / stats::sd(x) * lwd)
  return(x)
}

# This function returns the time elapsed
.runtime <- function(expression, name = NULL) {
  s1 <- Sys.time()
  eval(expression)
  s2 <- Sys.time()
  cat("\n", if (is.null(name)) NULL else paste0("[", name, "]"), "Runtime:", round(s2 - s1, 5), "seconds\n")
  return(invisible(as.numeric(s2 - s1)))
}

```

```{r edit mesh source}
getwd()
#setwd("C:\Users\brady\OneDrive\Documents\Academics\Art\rmdArtform_files")
#source('KD_sourceCodeFunctions.Rmd')
library(ggplot2)
library(aRtsy)



transformOptions <-c("perlin", "fbm", "simplex", "cubic","worley", "knn", "rf", "svm")
color = "black"
  background = "#fafafa"
transform = "fbm"
  #FIXME TRANSFORM OPTIONS c(
  #"perlin", "fbm", "simplex", "cubic",
  #"worley", "knn", "rf", "svm")

lines = 500 # 500 org
iterations = 500 # 500 org 
mixprob = 0 

# transform <- match.arg(transformOptions)
transform = 'perlin' #FIXME match.arg weird error 
# .checkUserInput(iterations = iterations, background = background) # take user input. check logical?  
artwork <- ggplot2::ggplot()
miny <- Inf
maxy <- -Inf

for (j in seq_along(colors)) { # for j in seq_along colors inputed 
  circle_points <- seq(from = -pi, to = pi, length.out = lines) # seq pi to pi, give back num of lines 
  start <- stats::runif(1, min = -10, max = 10)
  centers <- data.frame(x = 0:iterations, y = c(start, start + .bmline(n = iterations, lwd = stats::runif(1, min = 1, max = 10))))
  circle_centers <- predict(stats::loess(y ~ x, data = centers), newdata = centers) # use stats to estimate points for data 
  
  if (transform == "fbm") { # only special case if 'fbm' type transform? 
    radius <- data.frame(x = 1:lines, y = .bmline(n = lines, lwd = stats::runif(1, min = 0.5, max = 1)))
    circle_radius <- predict(stats::loess(y ~ x, data = radius), newdata = radius)
  } else {
    circle_radius <- c(.noise(c(1, lines), type = transform, limits = c(0.5, 1)))
  }
  # end of if transform is fbm 
  
  radius_increase <- data.frame(x = 1:lines, y = stats::rnorm(lines, mean = 0, sd = stats::runif(1, min = 0.01, max = 0.5)))
  circle_radius_increase <- predict(stats::loess(y ~ x, data = radius_increase), newdata = radius_increase)
  
  # creation of X var 
  x <- rep(0:iterations, each = lines) + 0.75 * cos(circle_points)
  mesh <- cpp_mesh(
    canvas = matrix(NA, nrow = lines * (iterations + 1), ncol = 2),
    points = circle_points,
    centers = circle_centers,
    iterations = iterations,
    start = start,
    order = seq_len(lines),
    radii = circle_radius,
    increase = circle_radius_increase
  ) 
  
  # if mixprob input is true
  if (mixprob > 0) {
    probs <- rep(1, length(colors))
    probs[j] <- probs[j] + 1 / mixprob
    col <- sample(colors, size = length(mesh[, 1]), replace = TRUE, prob = probs)
  } else {
    col <- colors(j) # was []
  }
  
  # create custom df from x generated from rep(), and 'y' created w/ custom function 
  df <- data.frame(x = x, y = mesh[, 1], z = mesh[, 2], col = col)
  if (min(df[["y"]]) < miny) miny <- min(df[["y"]])
  if (max(df[["y"]]) > maxy) maxy <- max(df[["y"]])
  
  # create artwork object 
  artwork <- artwork + ggplot2::geom_line(
    data = df,
    mapping = ggplot2::aes(x = x, y = y, group = z, col = col),
    alpha = 0.2, linewidth = 0.05
  )
} # end if 

# is this section creating the artwork or is it the artwork <- assignment above?
    # alternative artwork if the 'if' statement from line 229 is not executed
artwork <- artwork + ggplot2::scale_color_manual(values = colors) +
  ggplot2::scale_x_continuous(limits = c(-1, iterations + 1)) +
  ggplot2::scale_y_continuous(limits = c(miny - abs(maxy - miny) / 10, maxy + abs(maxy - miny) / 10))
artwork <- theme_canvas(artwork, background = background)

# originally a return statement for the function return(print(artwork))
print(artwork)
```


